import aenea.configuration

LOWERCASE = aenea.configuration.make_grammar_commands('base', {
    'alpha': 'a',
    'bravo': 'b',
    'charlie': 'c',
    'delta': 'd',
    'echo': 'e',
    'foxtrot': 'f',
    'golf': 'g',
    'hotel': 'h',
    'indigo': 'i',
    'juliet': 'j',
    'kilo': 'k',
    'lima': 'l',
    'mike': 'm',
    'november': 'n',
    'oscar': 'o',
    'poppa': 'p',
    'quiche': 'q',
    'romeo': 'r',
    'sierra': 's',
    'tango': 't',
    'uniform': 'u',
    'victor': 'v',
    'whiskey': 'w',
    'x-ray': 'x',
    'yankee': 'y',
    'zulu': 'z'
}, 'characters.lowercase')

UPPERCASE = aenea.configuration.make_grammar_commands('base', {
    'upper alpha': 'A',
    'upper bravo': 'B',
    'upper charlie': 'C',
    'upper delta': 'D',
    'upper echo': 'E',
    'upper foxtrot': 'F',
    'upper golf': 'G',
    'upper hotel': 'H',
    'upper indigo': 'I',
    'upper juliet': 'J',
    'upper kilo': 'K',
    'upper lima': 'L',
    'upper mike': 'M',
    'upper november': 'N',
    'upper oscar': 'O',
    'upper poppa': 'P',
    'upper quiche': 'Q',
    'upper romeo': 'R',
    'upper sierra': 'S',
    'upper tango': 'T',
    'upper uniform': 'U',
    'upper victor': 'V',
    'upper whiskey': 'W',
    'upper x-ray': 'X',
    'upper yankee': 'y',
    'upper zulu': 'Z'
}, 'characters.uppercase')

SYMBOLS = aenea.configuration.make_grammar_commands('base', {
    "amp": "ampersand",
    "ash": "slash",
    "at sign": "at",
    "back ash": "backslash",
    "backtick": "backtick",
    "bang": "exclamation",
    "bar": "bar",
    "cross": "plus",
    "dollar": "dollar",
    "dot": "dot",
    "comma": "comma",
    "eek": "equal",
    "hat": "caret",
    "hyph": "hyphen",
    "percent": "percent",
    "pound": "hash",
    "laip": "lparen",
    "raip": "rparen",
    "lace": "lbrace",
    "race": "rbrace",
    "lack": "lbracket",
    "rack": "rbracket",
    "quest": "question",
    "quote": "dquote",
    "rail": "underscore",
    "wink": "semicolon",
    "smote": "squote",
    "splat": "asterisk",
    "tilde": "tilde",
    "clap": "colon"
}, 'characters.symbols')

SYMBOLS_TEXT = aenea.configuration.make_grammar_commands('base', {
    "amp": "&",
    "ash": "/",
    "at sign": "@",
    "back ash": "\\",
    "backtick": "`",
    "bang": "!",
    "bar": "|",
    "cross": "+",
    "dollar": "$",
    "dot": ".",
    "comma": ",",
    "eek": "=",
    "hat": "^",
    "hyph": "-",
    "percent": "%%",
    "pound": "#",
    "laip": "(",
    "raip": ")",
    "lace": "{",
    "race": "}",
    "lack": "[",
    "rack": "]",
    "quest": "?",
    "quote": "\"",
    "rail": "_",
    "wink": ";",
    "smote": "'",
    "splat": "*",
    "tilde": "~",
    "clap": ":"
}, 'characters.symbols')

DIGITS = aenea.configuration.make_grammar_commands('base', {
    'zero': '0',
    'one': '1',
    'two': '2',
    'three': '3',
    'four': '4',
    'five': '5',
    'six': '6',
    'seven': '7',
    'eight': '8',
    'niner': '9'
}, 'characters.digits')
